### ISSUE TITLE
Confidence Score for the emotion

### ISSUE THREAD

**Issue by starshadow21** [GeorgiosIoannouCoder/vera#1]
Thank you for the great work!!

Any suggestion how to get the confidence score for the output emotion.

**Comment by GeorgiosIoannouCoder** [comment]
First, I would like to say a huge thank you for your kind words.

If I have understood correctly what you are looking for you can find it under **Section 4.4 Make and Evaluate New Predictions Using Our Testing Data** in the following Jupyter Notebook [https://nbviewer.org/github/GeorgiosIoannouCoder/vera/blob/main/backend/vera-notebook.ipynb](https://nbviewer.org/github/GeorgiosIoannouCoder/vera/blob/main/backend/vera-notebook.ipynb)!

As you can see in the above Jupyter Notebook, I am doing three feature extractions plus the original audio file which adds up to four rows for each audio file. When model.predict() is called, it returns the **probability** for each of the eight emotions. However, since we technically have four audio files for each user input audio file (due to the three feature extractions), we get probabilities for each emotion for each of these four audio files.

Doing more feature extractions, it makes our model more general and we can compare more emotions at the end to see which one to pick. However, it is best to do an even number of feature extractions so that together with the original audio file you get an odd number of predicted emotions and then use mode() to find the most common emotion. This is something that I did not do due to memory limitations however if the predicted emotions are [4 4 3 3], then mode() will fail.

Please let me know if this answers your question.
